"""Tier 5 White-Box Adversarial Test Suite (`adv_*`) for Totto, Mercedes F1 Fan Agent.

Generated by `challenger_r1_1` following the `test-coverage-audit` playbook.
Targets uncovered code paths, alias branches, OpenF1 HTTP/JSON failure modes,
weather override merging, envelope isolation, and direct CXAS ToolEvals/CallbackEvals
execution without modifying production source or `tests/`.
"""

from pathlib import Path
import sys
from typing import Any
from unittest.mock import MagicMock, patch

import pytest

PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(PROJECT_ROOT) not in sys.path:
  sys.path.insert(0, str(PROJECT_ROOT))

from tests.conftest import (  # pylint: disable=g-import-not-at-top
    AGENTS_DIR,
    APP_DIR,
    EVALS_DIR,
    EXPECTED_AGENTS,
    EXPECTED_TOOLS,
    DummyCallbackContext,
    load_before_agent_callback,
    load_tool_function,
    load_yaml_file,
)


# ==============================================================================
# 1. White-Box Adversarial Tests for `get_race_schedule`
# ==============================================================================


@pytest.mark.parametrize("calendar_kw", ["all", "calendar", "schedule", "season", "  SEASON  ", "Calendar"])
def test_adv_get_race_schedule_calendar_overview_keywords(calendar_kw: str) -> None:
  """Exercises all 4 calendar overview keywords ('all', 'calendar', 'schedule', 'season')."""
  get_race_schedule = load_tool_function("get_race_schedule")
  res = get_race_schedule(race_name=calendar_kw, user_location="London")
  assert res["status"] == "success"
  assert res["season"] == 2026
  assert len(res["featured_races"]) == 8
  assert res["result"]["status"] == "success"
  assert res["response"]["status"] == "success"


@pytest.mark.parametrize(
    "query_phrase,expected_race",
    [
        ("When is the Sakhir race?", "Bahrain Grand Prix"),
        ("Albert Park circuit schedule", "Australian Grand Prix"),
        ("Melbourne weekend", "Australian Grand Prix"),
        ("Japanese GP at Suzuka", "Japanese Grand Prix"),
        ("Florida sprint weekend", "Miami Grand Prix"),
        ("upcoming race weekend", "Miami Grand Prix"),
        ("current grand prix", "Miami Grand Prix"),
        ("Monte Carlo street circuit", "Monaco Grand Prix"),
        ("Great Britain GP", "British Grand Prix"),
        ("UK race weekend", "British Grand Prix"),
        ("Italy race at Monza", "Italian Grand Prix"),
        ("Las Vegas Strip night race", "Las Vegas Grand Prix"),
    ],
)
def test_adv_get_race_schedule_natural_language_substring_aliases(
    query_phrase: str, expected_race: str
) -> None:
  """Exercises natural-language substring matching across all alias keys (lines 418-421)."""
  get_race_schedule = load_tool_function("get_race_schedule")
  res = get_race_schedule(race_name=query_phrase, user_location="UTC")
  assert res["status"] == "success"
  assert res["race"]["race_name"] == expected_race
  assert res["needs_user_location"] is False


@pytest.mark.parametrize(
    "compound_location,expected_tz_prefix",
    [
        ("New York, NY (EDT)", "EDT"),
        ("Los Angeles, CA", "PDT"),
        ("San Francisco, California", "PDT"),
        ("Las Vegas, Nevada", "PDT"),
        ("London, UK (BST)", "BST"),
        ("Chicago / Central", "CDT"),
        ("Austin, Texas", "CDT"),
        ("Denver (MST)", "MDT"),
        ("Boston, MA", "EDT"),
        ("Seattle, WA", "PDT"),
        ("Rome, Italy", "CEST"),
        ("Monaco (CET)", "CEST"),
        ("Bahrain", "AST"),
        ("Melbourne, Australia", "AEST"),
        ("GMT", "GMT"),
    ],
)
def test_adv_get_race_schedule_compound_and_punctuated_user_locations(
    compound_location: str, expected_tz_prefix: str
) -> None:
  """Exercises punctuation stripping and multi-word/token timezone resolution (lines 466-476)."""
  get_race_schedule = load_tool_function("get_race_schedule")
  res = get_race_schedule(race_name="miami", user_location=compound_location)
  assert res["status"] == "success"
  assert res["needs_user_location"] is False
  assert res["resolved_timezone"].startswith(expected_tz_prefix)
  assert "agent_action" not in res


def test_adv_get_race_schedule_weather_override_branch() -> None:
  """Exercises the live_probe weather_override merge branch (lines 440-445)."""
  import importlib.util

  code_path = APP_DIR / "tools" / "get_race_schedule" / "python_function" / "python_code.py"
  spec = importlib.util.spec_from_file_location("adv_sched_weather", code_path)
  assert spec and spec.loader
  mod = importlib.util.module_from_spec(spec)
  spec.loader.exec_module(mod)

  with patch.object(
      mod,
      "_probe_openf1_meetings",
      return_value={
          "live_ok": True,
          "weather_override": {"condition": "Heavy tropical downpour", "rain_chance_percent": 95},
      },
  ):
    res = mod.get_race_schedule(race_name="miami", user_location="London")
    assert res["status"] == "success"
    assert res["data_source"] == "openf1_live"
    assert res["race"]["weather"]["condition"] == "Heavy tropical downpour"
    assert res["race"]["weather"]["rain_chance_percent"] == 95
    assert res["race"]["weather"]["temperature_c"] == 29  # Preserved from base fixture


@pytest.mark.parametrize(
    "mock_resp_factory",
    [
        lambda: MagicMock(status_code=429, json=lambda: {"detail": "Rate limited"}),
        lambda: MagicMock(status_code=503, json=lambda: {"detail": "Unavailable"}),
        lambda: MagicMock(status_code=200, json=lambda: []),
        lambda: MagicMock(status_code=200, json=lambda: {"unexpected": "dict"}),
        lambda: MagicMock(status_code=200, json=MagicMock(side_effect=ValueError("Malformed JSON"))),
    ],
)
def test_adv_get_race_schedule_openf1_non200_empty_and_malformed_json_fallback(
    mock_resp_factory: Any,
) -> None:
  """Exercises _probe_openf1_meetings when HTTP status != 200, JSON is empty [], dict, or invalid."""
  import requests

  get_race_schedule = load_tool_function("get_race_schedule")
  with patch.object(requests, "get", side_effect=lambda *a, **kw: mock_resp_factory()):
    res = get_race_schedule(race_name="monaco", user_location="London")
    assert res["status"] == "success"
    assert res["data_source"] == "openf1_fallback_fixture"
    assert res["race"]["race_name"] == "Monaco Grand Prix"


# ==============================================================================
# 2. White-Box Adversarial Tests for `get_driver_standings`
# ==============================================================================


@pytest.mark.parametrize(
    "cat_alias,expected_canonical",
    [
        ("driver", "drivers"),
        ("wdc", "drivers"),
        ("WDC", "drivers"),
        ("constructor", "constructors"),
        ("teams", "constructors"),
        ("team", "constructors"),
        ("wcc", "constructors"),
        ("WCC", "constructors"),
        ("both", "both"),
        ("all", "both"),
        ("results", "results"),
        ("recent", "results"),
        ("performance", "results"),
    ],
)
def test_adv_get_driver_standings_all_category_aliases(
    cat_alias: str, expected_canonical: str
) -> None:
  """Exercises all 13 category aliases in get_driver_standings (lines 33-47)."""
  get_driver_standings = load_tool_function("get_driver_standings")
  res = get_driver_standings(category=cat_alias, team_filter="Mercedes")
  assert res["status"] == "success"
  assert res["category"] == expected_canonical
  assert res["result"]["category"] == expected_canonical


@pytest.mark.parametrize(
    "team_kw,expected_driver_count,expected_driver_substr",
    [
        ("McLaren", 2, "Lando Norris"),
        ("Ferrari", 1, "Charles Leclerc"),
        ("Red Bull", 1, "Max Verstappen"),
        ("all", 6, "Lando Norris"),
        ("grid", 6, "Oscar Piastri"),
        ("any", 6, "George Russell"),
        ("petronas", 6, "Kimi Antonelli"),
        ("amg", 6, "George Russell"),
        ("russell", 6, "George Russell"),
        ("antonelli", 6, "Kimi Antonelli"),
    ],
)
def test_adv_get_driver_standings_team_filter_driver_filtering_and_keywords(
    team_kw: str, expected_driver_count: int, expected_driver_substr: str
) -> None:
  """Exercises team_filter keyword matching and filtered_drivers list (lines 175-244)."""
  get_driver_standings = load_tool_function("get_driver_standings")
  res = get_driver_standings(category="drivers", team_filter=team_kw)
  assert res["status"] == "success"
  assert len(res["driver_standings"]) == expected_driver_count
  assert expected_driver_substr in str(res["driver_standings"])
  # Mercedes drivers must ALWAYS be highlighted even when filtering by a rival team
  assert len(res["mercedes_drivers"]) == 2


@pytest.mark.parametrize(
    "mock_resp_factory",
    [
        lambda: MagicMock(status_code=429, json=lambda: {}),
        lambda: MagicMock(status_code=200, json=lambda: []),
        lambda: MagicMock(status_code=200, json=MagicMock(side_effect=ValueError("Corrupt JSON"))),
    ],
)
def test_adv_get_driver_standings_openf1_edge_responses(mock_resp_factory: Any) -> None:
  """Exercises _probe_openf1_drivers with HTTP 429, empty list [], and corrupt JSON."""
  import importlib.util
  import requests

  code_path = APP_DIR / "tools" / "get_driver_standings" / "python_function" / "python_code.py"
  spec = importlib.util.spec_from_file_location("adv_standings_edge", code_path)
  assert spec and spec.loader
  mod = importlib.util.module_from_spec(spec)
  spec.loader.exec_module(mod)

  with patch.object(requests, "get", side_effect=lambda *a, **kw: mock_resp_factory()):
    res = mod.get_driver_standings(category="drivers", team_filter="Mercedes")
    assert res["status"] == "success"
    assert res["data_source"] == "openf1_fallback_fixture"


# ==============================================================================
# 3. White-Box Adversarial Tests for Merch & Links Tools
# ==============================================================================


@pytest.mark.parametrize(
    "req_alias,expected_type",
    [
        ("return", "return"),
        ("returns", "return"),
        ("refund", "return"),
        ("exchange", "exchange"),
        ("exchanges", "exchange"),
        ("size_exchange", "exchange"),
        ("size exchange", "exchange"),
        ("swap", "exchange"),
        ("damaged_item", "damaged_item"),
        ("damaged item", "damaged_item"),
        ("damaged", "damaged_item"),
        ("damage", "damaged_item"),
        ("defective", "damaged_item"),
        ("replace", "damaged_item"),
        ("replacement", "damaged_item"),
    ],
)
def test_adv_submit_merch_request_all_type_aliases(
    req_alias: str, expected_type: str
) -> None:
  """Exercises all 15 request_type aliases in submit_merch_request (lines 40-54, 79)."""
  submit_fn = load_tool_function("submit_merch_request")
  res = submit_fn(order_number="1003", request_type=req_alias)
  assert res["status"] == "success"
  assert res["order_number"] == "MERC-1003"
  assert res["request_type"] == expected_type
  assert res["reference_id"] == f"MERC-REQ-1003-{expected_type.upper()}"
  assert res["item_name"] == "Mercedes-AMG PETRONAS Team Softshell Jacket"
  assert res["reason"] == f"Customer requested {expected_type}"


@pytest.mark.parametrize(
    "oos_keyword",
    ["signed", "race suit", "helmet", "paddock pass", "limited edition"],
)
def test_adv_check_merch_availability_all_archive_out_of_stock_keywords(
    oos_keyword: str,
) -> None:
  """Exercises all 5 out-of-stock archive item keywords (lines 84-96, 144-164)."""
  check_avail = load_tool_function("check_merch_availability")
  res = check_avail(item_query=oos_keyword, size="L")
  assert res["status"] == "error"
  assert res["in_stock"] is False
  assert res["available_sizes"] == []
  assert res["requested_size"] == "L"
  assert res["official_store_url"] == "https://shop.mercedesamgf1.com/"
  assert len(res["agent_action"]) > 15


@pytest.mark.parametrize(
    "item_query,size_input,expected_size",
    [
        ("russell cap", "os", "os"),
        ("russell cap", "default", "default"),
        ("russell cap", "one size", "one size"),
        ("russell cap", "ONE SIZE", "ONE SIZE"),
        ("russell cap", "", "One Size"),
        ("w17 model", "1:18 scale", "1:18 scale"),
        ("w17 model", "", "1:18 Scale"),
        ("kimi 12", "xl", "xl"),
    ],
)
def test_adv_check_merch_availability_size_aliases_and_defaults(
    item_query: str, size_input: str, expected_size: str
) -> None:
  """Exercises One Size aliases ('os', 'default') and empty size fallback (lines 168-200)."""
  check_avail = load_tool_function("check_merch_availability")
  res = check_avail(item_query=item_query, size=size_input)
  assert res["status"] == "success"
  assert res["in_stock"] is True
  assert res["requested_size"] == expected_size


@pytest.mark.parametrize(
    "link_alias,expected_cat",
    [
        ("ticket", "tickets"),
        ("f1 tickets", "tickets"),
        ("grandstand", "tickets"),
        ("hospitality", "tickets"),
        ("gear", "merch"),
        ("official", "team"),
        ("instagram", "social"),
        ("youtube", "social"),
        ("twitter", "social"),
        ("fans", "fan"),
        ("community", "fan"),
    ],
)
def test_adv_get_official_links_all_uncovered_aliases(
    link_alias: str, expected_cat: str
) -> None:
  """Exercises all remaining category aliases in get_official_links (lines 79-105)."""
  get_links = load_tool_function("get_official_links")
  res = get_links(category=link_alias)
  assert res["status"] == "success"
  assert res["category"] == expected_cat
  assert expected_cat in res["links"]


# ==============================================================================
# 4. White-Box Adversarial Tests for Direct CXAS `ToolEvals` & `CallbackEvals`
# ==============================================================================


def test_adv_cxas_scrapi_tool_evals_runner_executes_all_yaml_tests_cleanly() -> None:
  """Directly invokes cxas_scrapi's ToolEvals engine on evals/tool_tests/tool_tests.yaml."""
  from cxas_scrapi.evals.tool_evals import ToolEvals

  te = ToolEvals.__new__(ToolEvals)
  test_cases = te.load_tool_tests_from_dir(str(EVALS_DIR / "tool_tests"))
  assert len(test_cases) == 16
  for tc in test_cases:
    fn = load_tool_function(tc.tool)
    response = fn(**(tc.args or {}))
    failures_direct = te.validate_tool_test(tc, response)
    failures_wrapped = te.validate_tool_test(tc, {"response": response})
    assert not failures_direct, f"ToolEvals direct failure for {tc.name}: {failures_direct}"
    assert not failures_wrapped, f"ToolEvals wrapped failure for {tc.name}: {failures_wrapped}"


def test_adv_cxas_scrapi_callback_evals_runner_executes_cleanly() -> None:
  """Directly invokes cxas_scrapi's CallbackEvals engine on evals/callback_tests."""
  from cxas_scrapi.evals.callback_evals import CallbackEvals

  cb_evals = CallbackEvals()
  df = cb_evals.test_all_callbacks_in_app_dir(str(EVALS_DIR / "callback_tests"))
  assert len(df) == 4
  assert (df["status"] == "PASSED").all()


def test_adv_envelope_isolation_does_not_contain_circular_self_reference() -> None:
  """Verifies _with_envelope output across all 6 tools can be serialized to JSON without recursion."""
  import json

  for tool_name, kwargs in [
      ("get_race_schedule", {"race_name": "miami", "user_location": "London"}),
      ("get_driver_standings", {"category": "both", "team_filter": "Mercedes"}),
      ("lookup_merch_order", {"order_number": "MERC-1001"}),
      ("submit_merch_request", {"order_number": "MERC-1001", "request_type": "return"}),
      ("check_merch_availability", {"item_query": "polo", "size": "M"}),
      ("get_official_links", {"category": "all"}),
  ]:
    fn = load_tool_function(tool_name)
    out = fn(**kwargs)
    serialized = json.dumps(out)
    assert len(serialized) > 50
